name: release create

on:
  repository_dispatch:
    types:
      - release-create

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Python script with input value
      run: |
        output=$(python ./.github/workflows/version.py "2.24.100")
        
        # 실행 결과 값을 출력하여 GitHub Actions에 전달
        echo "NEW_VERSION=$output" >> $GITHUB_ENV

    - name: Get the result
      run: echo "Result is ${{ env.NEW_VERSION }}"  # 실행 결과 값을 출력하여 확인